### ISSUE TITLE
grid[0][0] is bottom left

### ISSUE THREAD

**Issue by xwyzhx** [yariza/Make-School-Arrays#2]
I just realized that grid[0][0] is bottom left, rather than top left, which is traditionally where it would be, and I've been telling students that grid[0][0] is top left. We should clarify in a note somewhere that in later uses of coordinate systems in tech, (0, 0) will commonly be at the top left corner to minimize confusion down the line.

**Comment by dionlarson** [comment]
I just added a note about this in 032cc32.

`grid[0][0] represents the bottom-left corner.`
